name: customized
data_path: /kaggle/working/splited_chest_xray # path to the dataset
preload_path: /kaggle/working/splited_chest_xray_preload # path to the preloaded data
save_path: ./runs/exp # path to save the experiment results
input_size: 512 # image resolution for the LPM
num_classes: 2 # number of classes
mean: 'auto' # 'auto' or a list of three numbers for RGB
std: 'auto' # 'auto' or a list of three numbers for RGB
learning_rate: 0.0001 # dataset-specific learning rate
